apiVersion: v1
kind: Service
metadata:
  name: taskflow-backend
spec:
  selector:
    app: taskflow-backend
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3001
