apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend
spec:
  selector:
    app: taskflow-frontend
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
